api_platform:
    title: api_symfony_jwt
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    enable_swagger: true  # Habilitar la documentación Swagger
    enable_swagger_ui: true  # Habilitar Swagger UI
